Updated

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,29 +1,29 @@
-pipeline {
-    agent any
+// pipeline {
+//     agent any
 
-    tools {
-        jdk 'jdk17'
-        nodejs 'node25'
-    }
+//     tools {
+//         jdk 'jdk17'
+//         nodejs 'node25'
+//     }
 
-    environment {
-        SCANNER_HOME = tool 'sonar-scanner'
-    }
+//     environment {
+//         SCANNER_HOME = tool 'sonar-scanner'
+//     }
 
-    stages {
+//     stages {
 
-        stage('Clean Workspace') {
-            steps {
-                cleanWs()
-            }
-        }
+//         stage('Clean Workspace') {
+//             steps {
+//                 cleanWs()
+//             }
+//         }
 
-        stage('Git Checkout') {
-            steps {
-                git branch: 'master',
-                    url: 'https://github.com/manikantanaveen232/DevOps-Project-Zomato-Kastro.git'
-            }
-        }
+//         stage('Git Checkout') {
+//             steps {
+//                 git branch: 'master',
+//                     url: 'https://github.com/manikantanaveen232/DevOps-Project-Zomato-Kastro.git'
+//             }
+//         }
 
         // stage('Install NPM Dependencies') {
         //     steps {
@@ -83,38 +83,99 @@ pipeline {
         //         }
         //     }
         // }
-stage('Deploy to EKS') {
+// stage('Deploy to EKS') {
+//     environment {
+//         AWS_DEFAULT_REGION = 'us-east-1'
+//         CLUSTER_NAME = 'Manikanta'
+//     }
+//     steps {
+//         withCredentials([[
+//             $class: 'AmazonWebServicesCredentialsBinding',
+//             credentialsId: 'aws-eks-creds'
+//         ]]) {
+//             sh '''
+//             echo "Updating kubeconfig..."
+//             aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
+
+//             echo "Deploying application to Kubernetes..."
+//             kubectl apply -f Kubernetes/deployment.yaml
+//             kubectl apply -f Kubernetes/node-service.yaml
+//             kubectl apply -f Kubernetes/service.yaml
+//             '''
+//         }
+//     }
+// }
+
+
+//     }
+
+//     post {
+//         always {
+//             echo 'Pipeline execution completed'
+//         }
+//         failure {
+//             echo 'Pipeline failed'
+//         }
+//     }
+// }
+pipeline {
+    agent any
+
     environment {
-        AWS_DEFAULT_REGION = 'us-east-1'
-        CLUSTER_NAME = 'Manikanta'
+        IMAGE_NAME = "myapp"
+        CONTAINER_NAME = "myapp-container"
     }
-    steps {
-        withCredentials([[
-            $class: 'AmazonWebServicesCredentialsBinding',
-            credentialsId: 'aws-eks-creds'
-        ]]) {
-            sh '''
-            echo "Updating kubeconfig..."
-            aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
 
-            echo "Deploying application to Kubernetes..."
-            kubectl apply -f Kubernetes/deployment.yaml
-            kubectl apply -f Kubernetes/node-service.yaml
-            kubectl apply -f Kubernetes/service.yaml
-            '''
+    stages {
+
+        stage('Clean Workspace') {
+            steps {
+                deleteDir()
+            }
         }
-    }
-}
 
+        stage('Checkout Code') {
+            steps {
+                git branch: 'main',
+                url: 'https://github.com/manikantanaveen232/DevOps-Project-Zomato-Kastro.git'
+            }
+        }
+
+        stage('Build Docker Image') {
+            steps {
+                sh 'docker build -t $IMAGE_NAME .'
+            }
+        }
+
+        stage('Stop Old Container') {
+            steps {
+                sh '''
+                docker stop $CONTAINER_NAME || true
+                docker rm $CONTAINER_NAME || true
+                '''
+            }
+        }
+
+        stage('Run New Container') {
+            steps {
+                sh '''
+                docker run -d \
+                --name $CONTAINER_NAME \
+                -p 3000:3000 \
+                $IMAGE_NAME
+                '''
+            }
+        }
 
     }
 
     post {
-        always {
-            echo 'Pipeline execution completed'
+        success {
+            echo 'Application Deployed Successfully'
         }
+
         failure {
-            echo 'Pipeline failed'
+            echo 'Deployment Failed'
         }
     }
 }
